- hosts: all
  become: yes
  tasks:
    - name: Cache update
      apt:
        update_cache: yes

- hosts: db,db_repl
  become: yes
  tasks:
    - name: Install PostgreSQL
      apt:
        name:
          - postgresql
          - postgresql-contrib
          - libpq-dev
          - python3-psycopg2
        state: present
        update_cache: yes

- hosts: db
  become: yes
  tasks:

    - name: Create database
      become: yes
      become_user: postgres
      postgresql_db:
        name: "{{DB_DATABASE}}"
        state: present

    - name: Create table email
      become_user: postgres
      community.postgresql.postgresql_table:
        db: "{{DB_DATABASE}}"
        name: email
        columns:
          - id serial primary key
          - email varchar(30) not null

    - name: Create table PhoneNumbers
      become_user: postgres
      community.postgresql.postgresql_table:
        db: "{{DB_DATABASE}}"
        name: phonenumbers
        columns:
          - id serial primary key
          - phone varchar(20) not null

    - name: Create db_repl_user
      become_user: postgres
      community.postgresql.postgresql_user:
        name: "{{DB_REPL_USER}}"
        password: "{{DB_REPL_PASSWORD}}"
        role_attr_flags: REPLICATION,LOGIN

    - name: Find path to pg_hba.conf
      become_user: postgres
      command: psql -t -P format=unaligned -c 'show hba_file'
      register: pg_hba_path

    - name: Add content to pg_hba.conf
      become_user: postgres
      lineinfile:
        path: "{{ pg_hba_path.stdout }}"
        insertafter: EOF
        state: present
        create: yes
        line: "{{ lookup('file', './pg_hba.conf') }}"

    - name: Create archive directory
      ansible.builtin.file:
        path: "{{archive_dir}}"
        state: directory
        owner: "{{DB_USER}}"
        mode: 0750

    - name: Get path to postgresql.conf
      command: su - postgres -c "psql -t -P format=unaligned -c 'show config_file'"
      register: postgres_conf_path

    - name: Setup postgresql.conf
      become_user: postgres
      ansible.builtin.blockinfile:
        path: "{{postgres_conf_path.stdout}}"
        block: "{{ lookup('file', './postgresql.conf') }}"
        create: yes

    - name: Restart PostgreSQL
      service:
        name: postgresql
        state: restarted


- hosts: db_repl
  become: yes
  tasks:
    - name: Get path to postgresql.conf
      command: su - postgres -c "psql -t -P format=unaligned -c 'show config_file'"
      register: postgres_conf_path

    - name: Configuration postgresql.conf
      ansible.builtin.blockinfile:
        path: "{{ postgres_conf_path.stdout }}"
        block: |
          listen_addresses = 'localhost, {{ inventory_db_repl_host }}'
          port = {{ DB_REPL_PORT }}
        create: yes

    - name: Stop PostgreSQL service
      ansible.builtin.service:
        name: postgresql
        state: stopped

    - name: Get directory for backup
      command: pg_lsclusters --json | jq '.[].pgdata' | awk '{gsub(/\"/, "", $1); print $1}'
      register: data_dir

    - name: Clean up directory
      ansible.builtin.file:
        state: "{{ item }}"
        path: "{{ data_dir.stdout }}"
        owner: "{{ DB_USER }}"
        group: postgres
        mode: "0750"
      loop:
        - absent
        - directory
      become: yes
      become_user: root

    - name: Execute pg_basebackup
      ansible.builtin.command:
        cmd: >
          pg_basebackup -v -R
          -h {{ hostvars['db'].ansible_host }} -p {{ DB_PORT }}
          -U {{ DB_REPL_USER }} -w -P
          -D {{ data_dir.stdout }}
      environment:
        PGPASSWORD: "{{ DB_REPL_PASSWORD }}"

    - name: Start PostgreSQL service
      ansible.builtin.service:
        name: postgresql
        state: started

- hosts: bot
  tasks:
    - name: Git clone bot repo
      ansible.builtin.git:
        repo: https://github.com/Sasherer/DevOps_bot.git
        version: main
        dest: "{{bot_directory}}"
        clone: yes

    - name: Install Python requirements
      pip:
        requirements: /opt/bot/requirements.txt

    - name: Bot environment
      ansible.builtin.copy:
        content: |
          TOKEN={{telegram.token}}
          RM_HOST={{RM_HOST}}
          RM_PORT={{RM_PORT}}
          RM_USER={{RM_USER}}
          RM_PASSWORD={{RM_PASSWORD}}
          DB_USER={{DB_USER}}
          DB_PASSWORD={{DB_PASSWORD}}
          DB_HOST={{DB_HOST}}
          DB_PORT={{DB_PORT}}
          DB_DATABASE={{DB_DATABASE}}
        dest: "/opt/bot/.env"

    - name: Bot start
      shell:
        cmd: python3 /opt/bot/bot.py
