- hosts: all  
  vars_files:
    -  classified_as_secret.yaml

- hosts: tg_bot
  become: yes
  tasks:
    - name: Clone repository Github from bot
      git:
        repo: https://github.com/Sasherer/DevOps_bot/tree/main
        dst: /opt/bot
        forse: yes
    - name: Install Python requirements
      pip:
        requirements: /opt/tg-bot/requirements.txt
    - name: Bot environment
      ansible.builtin.copy:
        content: |
          TOKEN={{telegram.token}}
          RM_HOST={{RM_HOST}}
          RM_PORT={{RM_PORT}}
          RM_USER={{RM_USER}
          RM_PASSWORD={{RM_PASSWORD}
          DB_USER={{DB_USER}}
          DB_PASSWORD={{DB_PASSWORD}}
          DB_HOST={{DB_HOST}}
          DB_PORT={{DB_PORT}}
          DB_DATABASE={{DB_DATABASE}}
        dest: "opt/bot/.env"
    - name: bot start
      shell: 
        cmd: python3 /opt/bot/bot.py

  -hosts: db
    become: yes
    tasks:
      -name: 